     
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: disable selinux
  include: disable-selinux.yaml
  when: disable_selinux

- name: install docker
  include: docker.yaml

- name: mount filesystems
  include: mounts.yaml

