name: space
dependencies:
  - python=3.10
  - cxx-compiler
  - fortran-compiler 
  - ccache
  - ipykernel
  - pip
  - numpy
  - pandas
  - scipy 
  - h5py
  - seaborn
  - numba
  - numexpr
  - solarmach
  - spiceypy
  - ipywidgets=IPW_VER
  - ipympl=IPYMPL_VER
  - pip:
    - matplotlib>=MIN_MPL_VER
    - git+https://github.com/spedas/pyspedas
    - git+https://github.com/MAVENSDC/PyTplot 
    - py_tsyganenko
    - jinja2
    - meson
    - ninja
    - scikit-learn
    - ipyparallel
    - astropy
    - sunpy
    - pycdfpp
    - pint
    - ffnet
    - git+https://github.com/SciQLop/speasy
    - cppyy
    - pyqtgraph<=0.12.2
    - jupyter_bokeh
    - sympy
    - ai.cdas

