---
- name: symlink /usr/bin/python -> /usr/bin/python3
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi
        if [ -f /usr/libexec/platform-python ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/libexec/platform-python /usr/bin/python; 
          ln --symbolic /usr/libexec/platform-python /usr/bin/python3; 
        fi
      become: true

- name: Base setup
  hosts: all
  remote_user: root
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
    - name: password
      prompt: What is your password?
  roles:
    - lpp_machine
    - centos
    - specific_setup
    - role: nvidia
      when: with_nvidia_gpu
    - jupyterhub
    - fail2ban
    
