---
- name: symlink /usr/bin/python -> /usr/bin/python3
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi
        if [ -f /usr/libexec/platform-python ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/libexec/platform-python /usr/bin/python; 
          ln --symbolic /usr/libexec/platform-python /usr/bin/python3; 
        fi
      become: true

- name: Base setup
  hosts: all
  remote_user: root
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
    - name: password
      prompt: What is your password?
  vars:
    jupyterhub_version: 1.4.2
    DockerSpawner:
      allowed_images:
        lpp/space: 'registry.lpp.polytechnique.fr/lpp/jupyter-notebok-space:hub-{{jupyterhub_version}}'
        lpp/hpc: 'registry.lpp.polytechnique.fr/lpp/jupyter-notebok-hpc:hub-{{jupyterhub_version}}'
        lpp/gpu: 'registry.lpp.polytechnique.fr/lpp/jupyter-notebok-gpu:hub-{{jupyterhub_version}}'
        jupyter/scipy-notebook: 'jupyter/scipy-notebook:hub-{{jupyterhub_version}}'
        jupyter/datascience-notebook: 'jupyter/datascience-notebook:hub-{{jupyterhub_version}}'
        cschranz/gpu-jupyter: 'cschranz/gpu-jupyter:latest'
      volumes:
        /DATA: '/DATA'
        /pplasma: '/pplasma'
        /mammouth: '/mammouth'
      mem_limit: "80g"
      cpu_percent: 50
      privileged: False
    disable_selinux: true
    install_mainline_kernel: false
    install_container_toolkit: true
    enable_jails: [sshd]
  roles:
    - lpp_machine
    - centos
    - specific_setup
    - nvidia
    - jupyterhub
    - fail2ban
    
