- name: Add docker repository
  get_url:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  ignore_errors: yes 
  register: command_result
  
- name: Add docker repository (backup)
  template:
    src: docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: '0644'
  when: "'failed' in command_result.msg"

- name: Install JupyterHub dependencies
  package:
    name: [docker-ce, docker-ce-cli, containerd.io]
    state: present

- name: Restart docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Add users to docker group
  ansible.builtin.lineinfile:
    path: /etc/security/group.conf
    regexp: '^\*;\*;\*;Al0000-2400;docker'
    insertafter: '^#xsh; tty\* ;%admin;Al0000-2400;plugdev'
    line: '*;*;*;Al0000-2400;docker'

- name: Enable pam_group module 
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^auth        required                                     pam_group.so'
    insertafter: '^auth        required                                     pam_faildelay.so delay=2000000'
    line: auth        required                                     pam_group.so