- name: Install JupyterHub dependencies
  package:
    name: [python3.5, python3.6, python3.7, python3.8, python3.10, python3-virtualenv.noarch, npm]
    state: present

- name: Add the user jupyter
  ansible.builtin.user:
    name: jupyter
    shell: /bin/bash
    groups: docker

- name: Create virtualenv folder
  ansible.builtin.file:
    path: /opt/virtual-envs
    state: directory
    mode: '0755'
    recurse: yes
    owner: jupyter
    group: jupyter

- name: Create user global dir for npm install
  ansible.builtin.file:
    path: $HOME/.npm-packages
    state: directory
    mode: '0755'
    recurse: yes
    owner: jupyter
    group: jupyter
  register: npm_dir

- name: "Configure npm to use {{ home }}/.npm-packages"
  shell: "npm config set prefix $HOME/.npm-packages"
  when: npm_dir.changed
  become: yes
  become_user: jupyter

- name: Create JupyterHub venv
  pip:
    name: [jupyterhub, dockerspawner ]
    virtualenv: /opt/virtual-envs/hub
    virtualenv_command: virtualenv
  become: yes
  become_user: jupyter

- name: Install JupyterHub sshauthenticator
  pip:
    name:  'https://github.com/andreas-h/sshauthenticator/archive/v0.1.zip'
    virtualenv: /opt/virtual-envs/hub
    virtualenv_command: virtualenv
  become: yes
  become_user: jupyter

- name: Install "configurable-http-proxy" node.js package globally.
  community.general.npm:
    name: configurable-http-proxy
    global: yes
  become: yes
  become_user: jupyter

- name: install hub config file
  template:
    src: jupyterhub_config.py.j2
    dest: $HOME/jupyterhub_config.py
    owner: jupyter
    group: jupyter
    mode: '0644'
  become: yes
  become_user: jupyter


