- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install docker
  include: docker.yaml

- name: mount filesystems
  include: mounts.yaml

- name: setup jupyterhub
  include: jupyterhub.yaml

- name: setup reverse proxy
  include: reverse-proxy.yaml