- name: Add docker repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install JupyterHub dependencies
  package:
    name: [python3.5, python3.6, python3.7, python3.8, python3.10, python3-virtualenv.noarch, npm, docker-ce, docker-ce-cli, containerd.io]
    state: present

- name: Restart docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Add users to docker group
  ansible.builtin.lineinfile:
    path: /etc/security/group.conf
    regexp: '^\*;\*;\*;Al0000-2400;docker'
    insertafter: '^#xsh; tty\* ;%admin;Al0000-2400;plugdev'
    line: '*;*;*;Al0000-2400;docker'

- name: Enable pam_group module 
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^auth        required                                     pam_group.so'
    insertafter: '^auth        required                                     pam_faildelay.so delay=2000000'
    line: auth        required                                     pam_group.so

- name: Add the user jupyter
  ansible.builtin.user:
    name: jupyter
    shell: /bin/bash
    groups: docker

- name: Create virtualenv folder
  ansible.builtin.file:
    path: /opt/virtual-envs
    state: directory
    mode: '0755'
    recurse: yes
    owner: jupyter
    group: jupyter

- name: Create user global dir for npm install
  ansible.builtin.file:
    path: $HOME/.npm-packages
    state: directory
    mode: '0755'
    recurse: yes
    owner: jupyter
    group: jupyter
  register: npm_dir

- name: "Configure npm to use {{ home }}/.npm-packages"
  shell: "npm config set prefix $HOME/.npm-packages"
  when: npm_dir.changed
  become: yes
  become_user: jupyter

- name: Create JupyterHub venv
  pip:
    name: [jupyterhub, dockerspawner]
    virtualenv: /opt/virtual-envs/hub
    virtualenv_command: virtualenv
  become: yes
  become_user: jupyter

- name: Install "configurable-http-proxy" node.js package globally.
  community.general.npm:
    name: configurable-http-proxy
    global: yes
  become: yes
  become_user: jupyter

- name: check if config file exists
  stat: 
    path: $HOME/jupyterhub_config.py
  register: jupyterhub_config
  become: yes
  become_user: jupyter

- name: "generate jupyterhub default config"
  shell: |
    cd $HOME 
    /opt/virtual-envs/hub/bin/jupyterhub --generate-config
  when: jupyterhub_config.stat.exists == False
  become: yes
  become_user: jupyter
  
- name: Set JupyterHub Spawner
  ansible.builtin.lineinfile:
    path: $HOME/jupyterhub_config.py
    regexp: '^c.JupyterHub.spawner_class ='
    insertafter: '^# c.JupyterHub.spawner_class = '
    line: c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
  become: yes
  become_user: jupyter

- name: Set JupyterHub IP
  ansible.builtin.lineinfile:
    path: $HOME/jupyterhub_config.py
    regexp: '^c.JupyterHub.hub_ip ='
    insertafter: '^# c.JupyterHub.hub_ip = '
    line: c.JupyterHub.hub_ip = '{{ ansible_default_ipv4.address }}'
  become: yes
  become_user: jupyter
