name: tensorflow
channels:
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - cxx-compiler
  - fortran-compiler 
  - ccache
  - pip
  - pip:
    - matplotlib>=MIN_MPL_VER
    - ipywidgets==IPW_VER
    - ipympl==IPYMPL_VER
    - pandas_profiling
    - scikit-learn
    - ipyparallel
    - handcalcs 
    - jupyter_bokeh
    - ipykernel
    - pandas
    - scipy
    - seaborn
    - ipyevents
    - nvidia-cudnn-cu11==8.6.0.163
    - tensorflow==2.12.*
  - cudatoolkit=11.8.0
  - scalene
  - cuda-nvcc
variables:
  XLA_FLAGS: "--xla_gpu_cuda_data_dir=/opt/conda/envs/tensorflow/lib/"