name: hpc
channels:
  - nvidia
dependencies:
  - python=3.10
  - cxx-compiler
  - fortran-compiler 
  - ccache
  - ipywidgets=IPW_VER
  - ipympl=IPYMPL_VER
  - pip
  - pip:
    - jinja2
    - matplotlib>=MIN_MPL_VER
    - scikit-learn==1.1.2
    - ipyparallel==8.4.1
    - LightPipes==2.1.3 
    - handcalcs==1.6.0 
    - plasmapy==0.8.1
    - cppyy==2.4.0
    - sympy==1.11
    - numpy==1.22.4
    - pandas==1.4.3
    - scipy==1.9.1
    - seaborn==0.11.2
    - ipyevents==2.0.1
    - tqdm==4.64.0
    - pytz==2022.2.1
    - pyzmq==23.2.1
    - pyparsing==3.0.9
    - Pillow==9.2.0
    - traitlets==5.3.0
    - nbconvert==6.5.3
    - voila==0.3.6
    - numba==0.56.0
    - llvmlite==0.39.0
  - h5py
  - cupy
  - cudatoolkit
  - cudnn
  - numexpr
  - mayavi
  - jupyter_bokeh
  - scalene
  - jaxlib=*=*cuda*
  - jax
  - cuda-nvcc

