name: hpc
dependencies:
  - python=3.10
  - ipykernel
  - pip
  - numpy
  - pandas
  - scipy
  - h5py
  - tensorflow-gpu
  - cupy
  - cudatoolkit
  - cudnn
  - seaborn
  - numba
  - numexpr
  - cppyy
  - pip:
    - jinja2
    - matplotlib>=MIN_MPL_VER
    - ipywidgets==IPW_VER
    - ipympl==IPYMPL_VER
    - pandas_profiling
    - scikit-learn
    - ipyparallel
    - LightPipes 
    - handcalcs 
    - geopack 
    - PyGeopack
    - plasmaspy
    - aidapy
    - git+https://github.com/UCLA-Plasma-Simulation-Group/pyVisOS.git@dev
