name: hpc
dependencies:
  - python=3.10
  - cxx-compiler
  - fortran-compiler 
  - ccache
  - ipykernel
  - pip
  - numpy
  - pandas
  - scipy
  - h5py
  - tensorflow-gpu
  - cupy
  - cudatoolkit
  - cudnn
  - seaborn
  - numba
  - numexpr
  - mayavi
  - ipyevents
  - pip:
    - jinja2
    - matplotlib>=MIN_MPL_VER
    - ipywidgets==IPW_VER
    - ipympl==IPYMPL_VER
    - pandas_profiling
    - scikit-learn
    - ipyparallel
    - LightPipes 
    - handcalcs 
    - geopack 
    - PyGeopack
    - plasmapy
    - aidapy
    - cppyy
    - jupyter_bokeh
    - sympy
